let houses = [
  {
    id: 1,
    name: "Cozy Cottage in the Woods",
    location: "Aspen, Colorado",
    price_per_night: 250,
    rating: 4.7,
    amenities: ["Wi-Fi", "Fireplace", "Mountain View", "Hiking Trails"],
    image_url: "https://example.com/image1.jpg",
  },
  {
    id: 2,
    name: "Luxury Villa with Private Pool",
    location: "Bali, Indonesia",
    price_per_night: 500,
    rating: 4.9,
    amenities: ["Wi-Fi", "Private Pool", "Ocean View", "Spa"],
    image_url: "https://example.com/image2.jpg",
  },
  {
    id: 3,
    name: "Historic Mansion in the City",
    location: "London, England",
    price_per_night: 600,
    rating: 4.8,
    amenities: ["Wi-Fi", "Garden", "Jacuzzi", "City View"],
    image_url: "https://example.com/image3.jpg",
  },
  {
    id: 4,
    name: "Ski Chalet with Hot Tub",
    location: "Whistler, Canada",
    price_per_night: 350,
    rating: 4.6,
    amenities: ["Wi-Fi", "Hot Tub", "Ski-in/Ski-out", "Mountain View"],
    image_url: "https://example.com/image4.jpg",
  },
  {
    id: 5,
    name: "Beach House with Panoramic Ocean Views",
    location: "Maui, Hawaii",
    price_per_night: 700,
    rating: 5.0,
    amenities: [
      "Wi-Fi",
      "Private Beach Access",
      "Infinity Pool",
      "Sunset Deck",
    ],
    image_url: "https://example.com/image5.jpg",
  },
  {
    id: 6,
    name: "Rustic Cabin Retreat",
    location: "Yellowstone  , Wyoming",
    price_per_night: 300,
    rating: 4.5,
    amenities: ["Wi-Fi", "Firepit", "Wildlife Viewing", "Secluded"],
    image_url: "https://example.com/image6.jpg",
  },
  {
    id: 7,
    name: "Modern Loft in the Heart of the City",
    location: "New York City, NY",
    price_per_night: 400,
    rating: 4.8,
    amenities: ["Wi-Fi", "Rooftop Terrace", "City View", "Fitness Center"],
    image_url: "https://example.com/image7.jpg",
  },
  {
    id: 8,
    name: "Treehouse Retreat",
    location: "Costa Rica",
    price_per_night: 200,
    rating: 4.7,
    amenities: ["Wi-Fi", "Canopy Beds", "Rainforest Views", "Outdoor Shower"],
    image_url: "https://example.com/image8.jpg",
  },
  {
    id: 9,
    name: "Seaside Cottage with Private Pier",
    location: "Sydney, Australia",
    price_per_night: 450,
    rating: 4.9,
    amenities: ["Wi-Fi", "Private Pier", "Waterfront Deck", "BBQ Grill"],
    image_url: "https://example.com/image9.jpg",
  },
  {
    id: 10,
    name: "Mountain Chalet with Spectacular Views",
    location: "Swiss Alps",
    price_per_night: 600,
    rating: 4.8,
    amenities: ["Wi-Fi", "Sauna", "Panoramic Views", "Ski Shuttle"],
    image_url: "https://example.com/image10.jpg",
  },
  {
    id: 11,
    name: "Desert Oasis Villa",
    location: "Dubai, UAE",
    price_per_night: 800,
    rating: 4.9,
    amenities: ["Wi-Fi", "Private Pool", "Desert Views", "Gourmet Kitchen"],
    image_url: "https://example.com/image11.jpg",
  },
  {
    id: 12,
    name: "Lakefront Cabin with Boat Dock",
    location: "Lake Tahoe, California",
    price_per_night: 350,
    rating: 4.6,
    amenities: ["Wi-Fi", "Boat Dock", "Lake Views", "Fireplace"],
    image_url: "https://example.com/image12.jpg",
  },
  {
    id: 13,
    name: "Eco-Friendly Dome House",
    location: "Costa Rica",
    price_per_night: 180,
    rating: 4.7,
    amenities: ["Wi-Fi", "Solar Power", "Jungle Views", "Outdoor Kitchen"],
    image_url: "https://example.com/image13.jpg",
  },
  {
    id: 14,
    name: "Historic Townhouse in the Old City",
    location: "Rome, Italy",
    price_per_night: 300,
    rating: 4.8,
    amenities: ["Wi-Fi", "Historic Charm", "City Center", "Private Courtyard"],
    image_url: "https://example.com/image14.jpg",
  },
  {
    id: 15,
    name: "Cliffside Villa with Infinity Pool",
    location: "Santorini, Greece",
    price_per_night: 700,
    rating: 4.9,
    amenities: ["Wi-Fi", "Infinity Pool", "Caldera Views", "Private Terrace"],
    image_url: "https://example.com/image15.jpg",
  },
  {
    id: 16,
    name: "Countryside Farmhouse with Vineyard Views",
    location: "Tuscany, Italy",
    price_per_night: 400,
    rating: 4.7,
    amenities: ["Wi-Fi", "Vineyard Tours", "Farm-to-Table Meals", "Gardens"],
    image_url: "https://example.com/image16.jpg",
  },
];

export { houses };
